---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-app
  template:
    metadata:
      labels:
        app: blog-app
    spec:
      containers:
      - name: blog-app
        image: tadziz/webapp:1.0.108
        ports:
        - containerPort: 5000
        env:
        - name: POCKETBASE_URL
          value: "https://pocket.lanlab.xyz"
        - name: POCKETBASE_ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              name: blog-secrets
              key: POCKETBASE_ADMIN_EMAIL
        - name: POCKETBASE_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: blog-secrets
              key: POCKETBASE_ADMIN_PASSWORD
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: blog-app-service
  namespace: default
spec:
  selector:
    app: blog-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
