apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pocket-lanlab-xyz-cert
  namespace: default
spec:
  secretName: pocket-lanlab-xyz-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - pocket.lanlab.xyz
