apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pocket-lanlab-xyz-cert
  namespace: pocketbase
spec:
  secretName: pocket-lanlab-xyz-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - pocket.lanlab.xyz


