apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocketbase
  namespace: pocketbase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pocketbase
  template:
    metadata:
      labels:
        app: pocketbase
    spec:
      containers:
      - name: pocketbase
        image: ghcr.io/muchobien/pocketbase:latest
        ports:
        - containerPort: 8090
        env:
        - name: PB_PUBLIC_URL
          value: "https://pocket.lanlab.xyz"
        volumeMounts:
        - name: pb-data
          mountPath: /pb_data
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
      volumes:
      - name: pb-data
        persistentVolumeClaim:
          claimName: pocketbase-data
