apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pocketbase
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
  - hosts:
    - pocket.lanlab.xyz
    secretName: pocket-lanlab-xyz-tls
  rules:
  - host: pocket.lanlab.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pocketbase
            port:
              number: 8090
