---
apiVersion: v1
kind: Namespace
metadata:
  name: pocketbase
---
apiVersion: v1
kind: Service
metadata:
  name: pocketbase
  namespace: pocketbase
spec:
  selector:
    app: pocketbase
  ports:
  - port: 8090
    targetPort: 8090
    protocol: TCP
  type: ClusterIP
